#!/usr/bin/env bash

#This script checks if a host on the network is reachable by sending ICMP echo requests (pings) to the specified IP address.

if [ "$#" -ne 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi
